---

- hosts: all
  become: true
  tasks:

    - name: Install Apache2 package
      apt:
        name: apache2
        state: latest

    - name: Install php
      apt:
        name: libapache2-mod-php
        state: latest
          
