---

- hosts: all
  become: true
  pre_tasks:

    - name: Install updates (RedHat)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "RedHat"

    - name: Install updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

    - name: Install Apache and PHP for Ubuntu servers
      tags: apache2,apache,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache and PHP for RedHat servers
      tags: apache,httpd,RedHat
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "RedHat"

    - name: start httpd (RedHat)
      tags: apache,httpd,RedHat
      service: 
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "RedHat"    

    - name: Copy Default html file for website
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
           

- hosts: db_servers
  become: true
  tasks:

    - name: Install MariaDB package (RedHat)
      tags: RedHat,db,mariadb
      yum:
        name: mariadb
        state: latest
      when: ansible_distribution == "RedHat"

    - name: Install MariaDB package (Ubuntu)
      tags: Ubuntu,db,mariadb
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
